### ISSUE TITLE
Group log files into a folder after detectors are stopped

### ISSUE THREAD

**Issue by mwshafer** [DonLakeFlyer/MavlinkTagController2#14]
Would be nice if the logs from each start and stop of the detectors were dropped into a folder to make getting all the log files from a flight easier via scp.

**Comment by DonLakeFlyer** [comment]
Each detector start/stop for the same flight increments the file name: *.#.log. First start/stop: *.1.log, second *.2.log and so forth. Then you can wildcard the scp call filenames to get what you want in a single call.

**Comment by DonLakeFlyer** [comment]
Currently the logs from previous flights are not deleted. I can see how this causes problems with respect to wildcarding a scp call for the current flight. What can happen is you have say *.1.log from the current flight where you only started detectors once. But the previous flight still has a *.2.log set sitting there since you started twice there. I can change it such that the previous flight logs are deleted only if you start the detectors on a new flight. A flight being determined by a run of the controller. With that you can wildcard fully *.*.log to get all logs from last flight.

**Comment by mwshafer** [comment]
There are other files beyond log files though that are really helpful for debugging. The .config, .bin, and .threshold files would be helpful for offloading. Additionally, the detectors are currently writing out some .csv files for the spectrogram data. Those files will likely not be there in final versions of the code, but right now for debugging and checking noise they are super useful.

**Comment by DonLakeFlyer** [comment]
You should be able to wildcard the entire root directory to get everything. The only stuff in there is log files. If everything went into a directory called say "Logs" then you would still just wildcard in that dir to pull things. Or am I missing something. Are you talking about some other structure?

There are still some files like the .bin which are not indexed by start/stop count. Also the config files are not indexed to start/stop count. They are overwritten with each send of tags. I'll change that such that they index like the other logs. Also anything else you want indexed by start/stop count which comes out of the detector needs to be controlled by a path in the config file. Otherwise I have no control over the naming.

**Comment by mwshafer** [comment]
Okay. I didn’t know how to do wildcarding. I’m learning something new again. 

If you updated the indexing of the bin files I think we’ll be okay. What would be nice is if the most recent files were always indexed with 1  or some other fixed value so that we didn’t have to keep track of which index the RPI was on. That way something like

scp “dasl@10.0.1.3:/home/dasl/{*.1.threshold,*.1.log,*.1.bin,*.1.csv}" ${dirName}

would grab everything and always grab the most recent files. We could just run that command each time the drone lands to grab everything.

**Comment by DonLakeFlyer** [comment]
Every time you start the controller the indices start at 1 again. So basically every flight restarts the indices at 1. So you just wildcard the indices as well to get everything.

Can you change the detector such that the config file reads two new settings:
* logPath: The path where all logs files should be written to
* startIndex: The detector start index

Then whenever you write a file from the detector, .bin, .threshold, .whatever you should write it to the directory specified by the logPath. And with the format foo.startIndex.bar. That will keep all detector runs connected together by the start index.

I'll change the controller to start writing that to the config file leaving the dataRecordPath in there as well for now.

**Comment by mwshafer** [comment]
The detector already writes the .bin file to the config argument 'dataRecordPath'. That parameter will be deprecated.
 I will update this to now write the bin file to "<logPath>/data_record.<tagID>.<startIndex>.bin". The spectrogram csv files will be written something like "<logPath>/segment_spectro.<tagID>.<startIndex>.csv".
